name: textlint and spellckeck

on:
  push

jobs:
    textlint-and-spellcheck:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v4    
        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: '22.x'
        - name: Install dependencies
          run: npm install
        - name: Run textlint
          run: npx textlint '**/*.md'
        - name: Run spellchecker
          run: npx cspell '**/*.md'